Área de Trabalho/HyperTech/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products do
    resources :comments, only: %i[create destroy]
    get "myprod", to: "products#myprod"
  end
  resources :profiles, only: %i[new create]
  resources :webhooks, only: [:create]
  get "sucess", to: "checkout#sucess"
  get "cancel", to: "checkout#cancel"
  post "checkout/create", to: "checkout#create"
  get 'main/index'
  get "report", to: "relatorios#report"
  get "reportV", to: "relatorios#reportV"
  get "reportP", to: "relatorios#reportP"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "main#index"
end

Área de Trabalho/HyperTech/app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
    <%= current_user.username %> ||
    
    <%= current_user.roles.first.name %>


  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <li>
    <%= link_to "Editar Conta", edit_user_registration_path, class: "dropdown-item"%>
    </li>
     <li><hr class="dropdown-divider"></li>
     <li>
      <%= link_to "Informações do vendedor", new_profile_path, class: "dropdown-item" if current_user.has_role?(:vendedor) %>
     </li>
     <li><hr class="dropdown-divider"></li>
    <li>
    <%= link_to "Categorias", categories_path, class: "dropdown-item" if policy(:category).index? %>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
    <%= link_to "Relatorio de Clientes", report_path(format: :pdf), class: "dropdown-item" if current_user.has_role?(:admin) %>
    </li>
    <li>
    <%= link_to "Relatorio de Vendedores", reportV_path(format: :pdf), class: "dropdown-item" if current_user.has_role?(:admin) %>
    </li>
    <li>
    <%= link_to "Relatorio de Produtos", reportP_path(format: :pdf), class: "dropdown-item" if current_user.has_role?(:admin) %>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </li>
  </ul>
</div>

<% else %>

<%=link_to "Login", user_session_path, class: "btn btn-info btn-lg" %>

<% end %>

Área de Trabalho/HyperTech/app/views/layouts/_cart.html.erb
<% if user_signed_in? %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
    Carrinho
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <li class="dropdown-item">
       <% @cart.each do |product| %>
      <%= product.title %>
      <br>
    <% end %>
    <% if @cart.present? %>

    <%= button_to "Compre agora", checkout_create_path, remote: true, data: {disable_with: "validando..."}, class: "btn btn-warning" %>
    <% end %>
    </li>
  </ul>
</div>

<% end %>

Área de Trabalho/HyperTech/app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>

<div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<% end %>

<% if alert.present? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<% end %>

Área de Trabalho/HyperTech/app/views/layouts/_navbar.html.erb
<!--HEADER-->    
     <div id="header">
      <div class="container">
        <nav
          class="navbar navbar-expand-lg navbar-light justify-content-between"
        >

         <%= link_to root_path do %>
      <%= image_tag "home/logo2.png", class: "img-fluid" %>
           <% end %>
        <!--  <a class="navbar-brand" href="./index.html">
            <img src="./assets/logo.jpg" class="img-fluid" />
          </a> -->
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to "Torne-se um Vendedor", new_profile_path, class: "nav-link" if current_user.has_role?(:cliente) %>
                <%end%>
              </li>
              <li clas="nav-item">
              </li>
              <li class="nav-item">
                <%= link_to "Produtos", products_url, class:"nav-link" %>
              </li>
              <li class="nav-item">
              <%= render "layouts/account_links"%>
              </li>
             <li>
             |
             </li>
              <li class="nav-item">
            <%= render "layouts/cart"%>
            </li>
            </ul>
  
          
          </div>
        </nav>
      </div>
  </div>
    <!--//HEADER-->

Área de Trabalho/HyperTech/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HyperTech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "home/home","home/produtos.css","home/newstyle.css","form.css", "data-turbo-track": "reload" %>

    <link type="image/png" sizes="16x16" rel="icon" href="./assets/icon.png">
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!-- font awesome cdn link  -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

     <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />


  <!--importa o javascript necessário para o slide -->
    <%= javascript_include_tag "application.js", "home/main.js", "home/owl.carousel.min.js", "home/jquery.magnific-popup.min.js", 
    "home/isotope.pkgd.min.js","home/bootstrap.min.js","jquery.js","jquery_ujs.js", "home/magnify/jquery.magnific-popup.min.js", "home/home.js",
     "data-turbo-track": "reload", defer: true %>
     
  </head>

  <body>

  <%= render 'layouts/navbar'%>
<div class="container">
 <%= render 'layouts/flash_messages'%>

    <%= yield %>

</div>

  </body>
</html>

Área de Trabalho/HyperTech/app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>