Área de Trabalho/HyperTech/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products do
    resources :comments, only: %i[create destroy]
    get "myprod", to: "products#myprod"
  end
  resources :profiles, only: %i[new create]
  resources :webhooks, only: [:create]
  get "sucess", to: "checkout#sucess"
  get "cancel", to: "checkout#cancel"
  post "checkout/create", to: "checkout#create"
  get 'main/index'
  get "report", to: "relatorios#report"
  get "reportV", to: "relatorios#reportV"
  get "reportP", to: "relatorios#reportP"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "main#index"
end

Área de Trabalho/HyperTech/app/models/product.rb
class Product < ApplicationRecord
  
    belongs_to :category
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_one_attached :image

    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    scope :filter_by_category, -> (category_id) {where category_id: category_id if category_id.present? }

    def to_s
        title
    end

    monetize :price, as: :price_cents

    def to_builder
        Jbuilder.new do |product|
          product.price stripe_price_id
          product.quantity 1
        end
    end
    
    after_create do
        product = Stripe::Product.create(name: title)
        price = Stripe::Price.create(product: product, unit_amount: self.price, currency: self.currency )
        self.update_attribute(:stripe_product_id, product.id)
        self.update_attribute(:stripe_price_id, price.id)

      end
    
    after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
    def create_and_assign_new_stripe_price 
      price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: self.price, currency: self.currency )
      update(stripe_price_id: price.id)

    end

end

Área de Trabalho/HyperTech/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Paginable
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_product, only: %i[ edit update destroy ]



  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to product_url
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to product_url
  end

  # GET /products or /products.json
  def index
    
    @products = Product.includes([image_attachment: :blob], [:user], [:category]).filter_by_category(params[:category_id]).order(created_at: :desc).page(current_page).per(8)

    @categories = Category.all
    authorize @products
  end

  # GET /products/myproduct
  def myprod

    @products = Product.includes([image_attachment: :blob], [:user]).filter_by_category(params[:category_id]).order(created_at: :desc).page(current_page).per(8)
    authorize @products

  end

  # GET /products/1 or /products/1.json
  def show

    @product = Product.includes([comments: :user]).find(params[:id])
    authorize @product

  end

  # GET /products/new
  def new
    @product = current_user.products.new
    authorize @product
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.new(product_params)
    authorize @product

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Produto foi criado com sucesso" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Produto foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Produto foi excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price,:price_cents, :image, :category_id, :currency)
    end
end

Área de Trabalho/HyperTech/app/helpers/products_helper.rb
module ProductsHelper
end

Área de Trabalho/HyperTech/app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :title,label: "Nome do produto", input_html: { class: 'form-control', placeholder: "Digite o titulo do seu produto" } %> 
    <%= f.input :description, label: "Descrição do produto", input_html: { class: 'form-control', placeholder: "Digite a descrição do seu produto" } %>
    <%= f.input :image, label: "Imagem do produto: ", as: :file %>
    <%= f.input :price_cents,label: "Preço:", input_html: { class: 'form-control', placeholder: "Informe o preço aqui" } %>
    <%= f.association :category,label: "Escolha uma categoria:", label_method: :c_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"Criar Produto", class: "btn btn-primary" %>
  </div>

<% end %>

Área de Trabalho/HyperTech/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title"> <%= product.title %> </h3>
            <h6 class="card-subtitle">Vendedor: <%= product.user.username %></h6>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"><%= image_tag product.image, style: "width: 430px; height 600px;" %></div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">Descrição do Produto:</h4>
                    <p><%= product.description %></p>
                    <h2 class="mt-5">
                       R$ <%= (product.price_cents) %>
                    </h2>
                      
                        <% if @cart.include?(product) %>
                        <%= button_to "Remover do carrinho", remove_from_cart_path(product), method: :delete, class: "btn btn-primary" %>
                        <% else %>
                        <%= button_to "Adicionar ao carrinho", add_to_cart_path(product), class: "btn btn-primary" %>
                        <% end %>
                
                    <h3 class="box-title mt-5">Vendidos:  <%= product.sales_count %> </h3> 
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<style type="text/css">

body{
    background-color: #edf1f5;
    margin-top:20px;
}
.card {
    margin-bottom: 30px;
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid transparent;
    border-radius: 0;
}
.card .card-subtitle {
    font-weight: 300;
    margin-bottom: 10px;
    color: #8898aa;
}
.table-product.table-striped tbody tr:nth-of-type(odd) {
    background-color: #f3f8fa!important
}
.table-product td{
    border-top: 0px solid #dee2e6 !important;
    color: #728299!important;
}


</style>

Área de Trabalho/HyperTech/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

Área de Trabalho/HyperTech/app/views/products/index.html.erb
<!--<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Mostrar Produto", product, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Produto", new_product_path, class:"btn btn-success" if user_signed_in? if policy(:product).new? %>

-->


<div> 

<%= link_to "Meus Produtos", product_myprod_path(@products), class: "btn btn-primary" if policy(:product).myprod?%>


    <% @categories.each do |category|%>
    
    <%= link_to category.c_name, products_url(category_id: category.id ), class: "btn btn-outline-info" %>
  
    <% end %>

</div>
        <section class="produtos">
        
          <% @products.each do |product| %>
            <div class="destaque">
              <div class="img-container mb-3">
                <%= image_tag(product.image, style: "height:200px;, width: 200px;") %>
              </div>
              <h5 class="text-uppercase"><%= product.title %></h5>
              <p class="mb-0">
               
              </p>  
              <p><%= link_to "Mostrar o Produto", product, class: 'btn btn-outline-primary' %></p>

            </div>
          <%end%>
    
          </section>

           <%= render 'main/paginacao'%>

Área de Trabalho/HyperTech/app/views/products/myprod.html.erb
<h1>Meus Produtos</h1>

<%= link_to "Novo Produto", new_product_path, class:"btn btn-success" if user_signed_in? if policy(:product).new? %>

<section class="produtos">
  <% @products.each do |product|  %>
    <% if product.user.id == current_user.id %>
        
      <div class="destaque">
        <div class="img-container mb-3">
          <%= image_tag(product.image, style: "height:200px;, width: 200px;") %>
        </div>
        <h5 class="text-uppercase"><%= product.title %></h5>
          <p class="mb-0">
        
          </p>  
    
          <p>
         <%= link_to "Mostrar o Produto", product, class: 'btn btn-outline-primary' %>
          </p>

      </div>
    <%end%>
  <%end%>
    
 </section>

<%= render 'main/paginacao'%>

Área de Trabalho/HyperTech/app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Voltar para Produtos", products_path, class:"btn btn-secondary" %>
</div>

Área de Trabalho/HyperTech/app/views/products/show.html.erb
<%= render @product %>

<div class="botoes">
  <%= link_to "Editar esse Produto", edit_product_path(@product), class: "btn btn-warning" if policy(@product).update? %>  
  <%= button_to "Excluir esse Produto", @product, method: :delete, class:"btn btn-danger" if policy(@product).destroy? %> 
  <%= link_to "Voltar para Produtos", products_path, class: "btn btn-secondary" %> 
</div>

<h2 class="mt-3">Comentários:</h2>
<%= render @product.comments %>

<h2>Adicione um comentário:</h2>

<% if policy(:comment).create? %>
<%= render "comments/form"%>
<% else %>
<h3> Por favor, faça o login para criar um comentário. </h3>
<%end%>

<br>