Área de Trabalho/HyperTech/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products do
    resources :comments, only: %i[create destroy]
    get "myprod", to: "products#myprod"
  end
  resources :profiles, only: %i[new create]
  resources :webhooks, only: [:create]
  get "sucess", to: "checkout#sucess"
  get "cancel", to: "checkout#cancel"
  post "checkout/create", to: "checkout#create"
  get 'main/index'
  get "report", to: "relatorios#report"
  get "reportV", to: "relatorios#reportV"
  get "reportP", to: "relatorios#reportP"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "main#index"
end

Área de Trabalho/HyperTech/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = current_user
    
  end

  def create

     @profile = current_user
     

     if @profile.update(user_params)

      redirect_to root_path, notice: "Seus dados foram atualizados."

     else

      render :new

     end
  end

  private 

  def user_params

   params.require(:user).permit(:country, :adress,:cpf, :phone, :bank_account, role_ids: [])

  end
end

Área de Trabalho/HyperTech/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Área de Trabalho/HyperTech/app/views/profiles/new.html.erb
<% if user_signed_in? %>

<%if current_user.has_role?(:vendedor)%>
<h1>Atualize suas informações aqui:</h2>
<%end%>


<%= simple_form_for @profile, url: profiles_path, method: :post do |f| %>
 <%= f.error_notification %>

<%if current_user.has_role?(:cliente) %>
 <%= f.collection_check_boxes(:role_ids, Role.where(name: 'vendedor'), :id, :name) do |b|
  b.label{ b.check_box(checked: true) + b.text} end%>
 <%end%>
<%= f.input :country,label: "Estado", as: :string %>
<%= f.input :adress, label: "Endereço" %>
<%= f.input :phone, label: "Telefone" %>
<%= f.input :cpf, label: "Digite seu CPF:" %> 
<br>
<p><strong>Opcional: Nos forneça sua conta bancária para que possamos fazer os repasses mais facilmente.</strong></p>
<%= f.input :bank_account, label: "Informe sua conta bancária:" %> 

<br>

<%= f.submit "Forneça os dados restantes", class: "btn btn-primary"%>

<%end%>

<%end %>


<br>
<br>
<p align="center"><strong>REGRAS DO VENDEDOR</strong></p>
<br>
<ul>
<li><strong>* CADA VENDEDOR É RESPONSÁVEL POR SEU PRODUTO *</strong></li>
<li><strong>* É RESPONSABILIDADE DO VENDEDOR REALIZAR UM MEIO DE ENTREGA DE SEUS PRODUTOS *</strong></li>
<li><strong>* APOS A CONFIRMAÇÃOS DOS DADOS E TORNANDO-SE "VENDEDOR", É DE SUMA IMPORTANTCIA ENVIAR UM EMAIL PARA "0123guga@gmail.com" COM SEU NOME, TELEFONE E SEU PIX *</strong></li>
<li><strong>* O PAGAMENTO PARA O VENDEDOR DE SEUS PRODUTOS VENDIDOS, É FEITO VIA PIX OU CONTA BANCÁRIA (OPCIONAL) *</strong></li>
<li><strong>* CADA PRODUTO VENDIDO 15% DELE É DIRECIONADO PARA A PLATAFORMA *</strong></li>
</ul>